# Configuration for Release Notes

changelog:
  exclude-labels:
    - "skip-changelog"

  categories:
    - title: "🎵 New Features"
      labels:
        - "feature"
        - "enhancement"

    - title: "🐞 Bug Fixes"
      labels:
        - "bug"

    - title: "📚 Documentation Updates"
      labels:
        - "documentation"

    - title: "🧪 Testing"
      labels:
        - "test"

    - title: "🛠️ Maintenance"
      labels:
        - "maintenance"
        - "refactor"

  change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
  no-changes-template: "No significant changes in this release."

  include:
    contributors: true
    pull-requests: true
    commits: true

  contributor-template: '@$AUTHOR'
  contributors-title: "🌟 Contributors"

  commit-template: '- $MESSAGE by @$AUTHOR'
  exclude-commit-messages:
    - "Merge branch"
    - "Merge pull request"
